name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - '💥 Breaking Change'
  minor:
    labels:
      - '⭐ Feature'
  patch:
    labels:
      - '🐞 Bug Fix'
      - '🛠 Improvement'
      - '📖 Docs'
      - '🌍 i18n'
  default: patch

categories:
  - title: '💥 Breaking Changes'
    label: '💥 Breaking Change'

  - title: '⭐ Features'
    label: '⭐ Feature'

  - title: '🐞 Bug Fixes'
    label: '🐞 Bug Fix'

  - title: '🛠 Improvements'
    label: '🛠 Improvement'

  - title: '📖 Documentation'
    label: '📖 Docs'

  - title: '🌍 Localization'
    label: '🌍 i18n'

  - title: '🌀 External Changes'
    labels:
      - '🔌 3rd Party Plugin'
      - '📦 Dependencies'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'

template: |
  ## What's Changed

  $CHANGES

  ---

  **Full Changelog**: [`$PREVIOUS_TAG...v$RESOLVED_VERSION`]($REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)

exclude-labels:
  - 'Skip Release'