name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - type: pre-exclude
    when:
      label: 'Skip Release'

  - title: '💥 Breaking Changes'
    semver-increment: major
    when:
      label: '💥 Breaking Change'

  - title: '⭐ Features'
    semver-increment: minor
    when:
      label: '⭐ Feature'

  - title: '🐞 Bug Fixes'
    semver-increment: patch
    when:
      label: '🐞 Bug Fix'

  - title: '🛠 Improvements'
    semver-increment: patch
    when:
      label: '🛠 Improvement'

  - title: '📖 Documentation'
    semver-increment: patch
    when:
      label: '📖 Docs'

  - title: '🌍 Localization'
    semver-increment: patch
    when:
      label: '🌍 i18n'

  - title: '🌀 External Changes'
    when:
      labels:
        - '🔌 3rd Party Plugin'
        - '📦 Dependencies'

  - type: version-resolver
    semver-increment: patch

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&@#'
no-changes-template: '- No changes'

template: |
  ## What's Changed?

  $CHANGES

  ## New Contributors

  $NEW_CONTRIBUTORS

  ---

  **Full Changelog**: [`$PREVIOUS_TAG...v$RESOLVED_VERSION`]($REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)