changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - 💥 Breaking Change

    - title: 🌟 New Features
      labels:
        - 🌟 New Feature

    - title: ⭐ Features
      labels:
        - ⭐ Feature

    - title: 🐞 Bug Fixes
      labels:
        - 🐞 Bug Fix

    - title: 🛠 Improvements
      labels:
        - 🛠 Improvement

    - title: 🌀 External Changes
      labels:
        - 🔌 3rd Party Plugin

    - title: 📖 Documentation
      labels:
        - 📖 Docs

    - title: 🌍 Localization
      labels:
        - 🌍 i18n

  exclude:
    labels:
      - Skip Release
      - Internal
    authors:
      - dependabot
      - github-actions 